# Generated by Django 4.0.3 on 2022-04-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='urlmov',
            field=models.CharField(default='default urlmov', max_length=500),
            preserve_default=False,
        ),
    ]
