# Generated by Django 4.0.3 on 2022-04-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=-1.0, max_length=255, unique=True, verbose_name='Url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default={'slug': 1}, max_length=255, unique=True, verbose_name='Url'),
            preserve_default=False,
        ),
    ]
