# Generated by Django 4.0.3 on 2022-04-30 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Качество',
                'verbose_name_plural': 'Качество',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='actors',
            field=models.CharField(default=None, max_length=5000, verbose_name='Актеры'),
        ),
        migrations.AddField(
            model_name='post',
            name='director',
            field=models.CharField(default=None, max_length=50, verbose_name='Режиссер'),
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(default=None, max_length=3000, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='post',
            name='rateIMDB',
            field=models.CharField(default=None, max_length=3000, verbose_name='Рейтинг IMDB'),
        ),
        migrations.AddField(
            model_name='post',
            name='rateKP',
            field=models.CharField(default=None, max_length=3000, verbose_name='Рейтинг КП'),
        ),
        migrations.AddField(
            model_name='post',
            name='released',
            field=models.CharField(default=None, max_length=15, verbose_name='Год выхода'),
        ),
        migrations.AddField(
            model_name='post',
            name='side',
            field=models.CharField(default=None, max_length=50, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='post',
            name='translation',
            field=models.CharField(default=None, max_length=3000, verbose_name='Перевод'),
        ),
        migrations.AddField(
            model_name='post',
            name='quality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movie.quality', verbose_name='Качество'),
        ),
    ]
