# Generated by Django 4.0.3 on 2022-04-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_quality_post_actors_post_director_post_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='actors',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True, verbose_name='Актеры'),
        ),
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, default=None, max_length=3000, null=True, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='post',
            name='side',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Страна'),
        ),
    ]
