# Generated by Django 4.0.3 on 2022-04-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_alter_post_actors_alter_post_genre_alter_post_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='side',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна'),
        ),
    ]
