# Generated by Django 4.0.3 on 2022-04-30 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_alter_post_actors_alter_post_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='director',
            field=models.CharField(default='None', max_length=50, verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, default='None', max_length=3000, null=True, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='post',
            name='quality',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movie.quality', verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rateIMDB',
            field=models.CharField(default='None', max_length=3000, verbose_name='Рейтинг IMDB'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rateKP',
            field=models.CharField(default='None', max_length=3000, verbose_name='Рейтинг КП'),
        ),
        migrations.AlterField(
            model_name='post',
            name='released',
            field=models.CharField(default='None', max_length=15, verbose_name='Год выхода'),
        ),
        migrations.AlterField(
            model_name='post',
            name='side',
            field=models.CharField(blank=True, default='None', max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='post',
            name='translation',
            field=models.CharField(default='None', max_length=3000, verbose_name='Перевод'),
        ),
    ]
